config/routes.rb
CitizenBudgetModel::Engine.routes.draw do
  devise_for :users, class_name: 'CitizenBudgetModel::User', module: :devise

  resources :translations, only: [:index, :create] do
    collection do
      get :export
    end
  end

  resources :organizations

  resources :users, except: [:show, :destroy]

  resources :policy_tables do
    member do
      post :sort
      post :activate
    end

    resources :policy_sections, except: [:index] do
      member do
        post :sort
      end

      resources :economic_measures, except: [:index]
    end
  end

  resources :sensitivities do
    member do
      post :sort
      post :sort_variable
    end

    resources :variables, except: [:index]

    resources :sensitivity_sections, except: [:index] do
      member do
        post :sort
      end
      resources :impacts, except: [:index]
    end
  end

  resources :simulators do
    member do
      post :sort
      post :activate
    end

    resources :sections, except: [:index] do
      member do
        post :sort
      end

      resources :questions, except: [:index]
    end
  end

  resources :questions

  namespace :citizen_budget_model do
    get 'pages/home'
  end

  root to: 'pages#home'
end

app/models/citizen_budget_model/economic_measure.rb
module CitizenBudgetModel
  class EconomicMeasure < ActiveRecord::Base
    acts_as_list scope: :policy_section_id, top_of_list: 0
    translates :name, :unit_name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :policy_section
    belongs_to :question

    validates_presence_of :policy_section_id
    validates_presence_of :question_id
    validates :name, 'citizen_budget_model/locale' => true
    validates_uniqueness_of :machine_name, scope: :policy_section_id, allow_blank: true
    validates_format_of :machine_name, with: /\A[a-z_][a-z_0-9]*\z/, allow_blank: true
    validates_numericality_of :year_1_value, :year_2_value, allow_blank: true
  end
end

app/models/citizen_budget_model/impact.rb
module CitizenBudgetModel
  class Impact < ActiveRecord::Base
    acts_as_list scope: :sensitivity_section_id, top_of_list: 0
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :sensitivity_section
    has_many :impact_variables, -> { order(:year) }, dependent: :destroy
    accepts_nested_attributes_for :impact_variables

    validates_presence_of :sensitivity_section_id
    validates_format_of :machine_name, with: /\A[a-z_][a-z_0-9]*\z/, allow_blank: true
    # @see http://www.postgresql.org/docs/9.3/static/sql-keywords-appendix.html
    # Nokogiri::HTML(open(url).read).xpath('//table/tbody/tr[td[2][text()="reserved"]]/td[1]//text()').map{|s| s.to_s.downcase}
    validates_exclusion_of :machine_name, in: %w(all analyse analyze and any
      array as asc asymmetric both case cast check collate column constraint
      create current_catalog current_date current_role current_time
      current_timestamp current_user default deferrable desc distinct do else
      end except false fetch for foreign from grant group having in initially
      intersect into lateral leading limit localtime localtimestamp not null
      offset on only or order placing primary references returning select
      session_user some symmetric table then to trailing true union unique user
      using variadic when where window with), allow_blank: true

    def year_1
      impact_variables.where(:year => 'Year 1')
    end

    def year_2
      impact_variables.where(:year => 'Year 2')
    end

    def year_5
      impact_variables.where(:year => 'Year 5')
    end
  end
end

app/models/citizen_budget_model/impact_variable.rb
module CitizenBudgetModel
  class ImpactVariable < ActiveRecord::Base
    belongs_to :impact
    belongs_to :variable

    validates_presence_of :impact_id
    validates_presence_of :variable_id
  end
end

app/models/citizen_budget_model/multiplier.rb
module CitizenBudgetModel
  class Multiplier < ActiveRecord::Base
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    belongs_to :simulator
    has_many :policy_sections

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true

    # Returns the equation or a default equation if not set.
    #
    # @return [String] an equation
    def working_equation
      default_equation
    end

    # Returns a default equation, where the difference between the chosen value
    # and the default value is multiplied by the unit value for each variable.
    #
    # @return [String] a default equation
    def default_equation
      equation = []
      policy_sections.each do |section|
        section.policies.each do |policy|
          equation << policy.question.working_equation
        end
        #section.questions.each do |question|
          #equation << question.working_equation
        #end
      end
      equation.reject(&:empty?).join(' + ')
    end


  end
end

app/models/citizen_budget_model/organization.rb
module CitizenBudgetModel
  class Organization < ActiveRecord::Base
    acts_as_paranoid
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    has_many :simulators, dependent: :destroy
    has_many :policy_tables, dependent: :destroy
    has_many :sentivities, dependent: :destroy
    has_many :users

    validates :name, 'citizen_budget_model/locale' => true
  end
end

app/models/citizen_budget_model/policy.rb
module CitizenBudgetModel
  class Policy < ActiveRecord::Base
    acts_as_list scope: :policy_section_id, top_of_list: 0
    translates :name, :unit_name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :policy_section
    belongs_to :question

    validates_presence_of :policy_section_id
    validates_uniqueness_of :machine_name, scope: :policy_section_id, allow_blank: true
    validates_format_of :machine_name, with: /\A[a-z_][a-z_0-9]*\z/, allow_blank: true
    validates_numericality_of :default_value, :year_1_value, :year_2_value, :minimum, :maximum, allow_blank: true
    validates_numericality_of :step, greater_than: 0, allow_blank: true

    validate :all_or_none_of_minimum_and_maximum_and_step_should_be_present
    validate :minimum_must_be_less_than_maximum

    def all_or_none_of_minimum_and_maximum_and_step_should_be_present
      unless minimum.present? && maximum.present? && step.present? || minimum.blank? && maximum.blank? && step.blank?
        [:minimum, :maximum, :step].each do |attribute|
          if send(attribute).blank?
            errors.add(attribute, :blank)
          end
        end
      end
    end

    def minimum_must_be_less_than_maximum
      if minimum.present? && maximum.present? && minimum.to_f >= maximum.to_f
        errors.add(:minimum, _('must be less than maximum'))
      end
    end
  end
end

app/models/citizen_budget_model/policy_section.rb
module CitizenBudgetModel
  class PolicySection < ActiveRecord::Base
    acts_as_list scope: :policy_table_id, top_of_list: 0
    translates :name, :popover, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :policy_table
    has_many :economic_measures, -> { order(:position) }, dependent: :destroy

    validates_presence_of :policy_table_id
    validates :name, 'citizen_budget_model/locale' => true
  end
end

app/models/citizen_budget_model/policy_table.rb
module CitizenBudgetModel
  class PolicyTable < ActiveRecord::Base
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    belongs_to :simulator
    has_many :policy_sections, -> { order(:position) }, dependent: :destroy

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true
    validates_numericality_of :growth_forecast, :employment_coefficient, greater_than: 0, allow_blank: true

    # Sets the simulator as active and all others as inactive.
    def activate!
      self.class.where(active: true).each do |policy_table|
        policy_table.update!(active: false)
      end
      update!(active: true)
    end

  end
end

app/models/citizen_budget_model/section.rb
module CitizenBudgetModel
  class Section < ActiveRecord::Base
    acts_as_list scope: :simulator_id, top_of_list: 0
    translates :title, :description, :modal, :popover, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :simulator
    has_many :questions, -> { order(:position) }, dependent: :destroy

    validates_presence_of :simulator_id

    # Returns the section's title or "Untitled"
    #
    # @return [String] the section's title or "Untitled"
    def display_name
      title.present? && title || _('Untitled')
    end
  end
end

app/models/citizen_budget_model/sensitivity.rb
module CitizenBudgetModel
  class Sensitivity < ActiveRecord::Base
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    has_many :variables, -> { order(:position) }, dependent: :destroy
    has_many :sensitivity_sections, -> { order(:position) }, dependent: :destroy

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true

  end
end

app/models/citizen_budget_model/sensitivity_section.rb
module CitizenBudgetModel
  class SensitivitySection < ActiveRecord::Base
    acts_as_list scope: :sensitivity_id, top_of_list: 0
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :sensitivity
    has_many :impacts, -> { order(:position) }, dependent: :destroy

    validates_presence_of :sensitivity_id

  end
end

app/models/citizen_budget_model/simulator.rb
module CitizenBudgetModel
  class Simulator < ActiveRecord::Base
    acts_as_paranoid
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    has_many :sections, -> { order(:position) }, dependent: :destroy

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true
    validates_numericality_of :total_revenue, greater_than: 0, only_integer: true, allow_blank: true
    validates :equation, 'citizen_budget_model/equation' => true, allow_blank: true

    # Sets the simulator as active and all others as inactive.
    def activate!
      self.class.where(active: true).each do |simulator|
        simulator.update!(active: false)
      end
      update!(active: true)
    end

    # Returns the equation or a default equation if not set.
    #
    # @return [String] an equation
    def working_equation
      if equation?
        equation
      else
        default_equation
      end
    end

    # Returns a default equation, where the difference between the chosen value
    # and the default value is multiplied by the unit value for each variable.
    #
    # @return [String] a default equation
    def default_equation
      equation = []
      sections.each do |section|
        section.questions.each do |question|
          equation << question.working_equation
        end
      end
      equation.reject(&:empty?).join(' + ')
    end

    # Solves the equation with the given variables' values.
    #
    # @param [Hash{Symbol,String=>Float,String}] variables variables
    # @return [Float] a solution
    def solve(variables)
      keys = []
      values = []

      variables.each do |key,value|
        keys << key.to_sym
        values << Float(value)
      end

      # Struct will raise a NameError, whereas OpenStruct will not.
      eval(working_equation, Struct.new(*keys).new(*values).instance_eval{binding})
    end
  end
end

app/controllers/citizen_budget_model/devise_controller.rb
module CitizenBudgetModel
  class DeviseController < CitizenBudgetModelController
    layout 'citizen_budget_model/devise'

    def after_sign_in_path_for(resource)
      simulators_path
    end
  end
end

app/controllers/citizen_budget_model/economic_measures_controller.rb
module CitizenBudgetModel
  class EconomicMeasuresController < CitizenBudgetModelController
    before_action :authenticate_user!
    before_action :set_policy_table
    before_action :set_policy_section
    before_action :set_economic_measure, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
      @economic_measure = collection.new
    end

    def edit
    end

    def create
      @economic_measure = collection.new(economic_measure_params)

      if @economic_measure.save
        redirect_to [@policy_table, @policy_section, @economic_measure], notice: _('Economic Measure was created.')
      else
        render :new
      end
    end

    def update
      if @economic_measure.update(economic_measure_params)
        redirect_to [@policy_table, @policy_section, @economic_measure], notice: _('Economic Measure was updated.')
      else
        render :edit
      end
    end

    def destroy
      @economic_measure.destroy
      redirect_to [@policy_table, @policy_section], notice: _('Economic Measure was deleted.')
    end

  private

    def collection
      @collection ||= @policy_section.economic_measures
    end

    def set_policy_table
      @policy_table = policy_tables.find(params[:policy_table_id])
    end

    def set_policy_section
      @policy_section = @policy_table.policy_sections.find(params[:policy_section_id])
    end

    def set_economic_measure
      @economic_measure = collection.find(params[:id])
    end

    def economic_measure_params
      attribute_names = EconomicMeasure.globalize_attribute_names + [:machine_name, :year_1_value, :year_2_value, :question_id]
      params.require(:economic_measure).permit(*attribute_names)
    end
  end
end

app/controllers/citizen_budget_model/impacts_controller.rb
module CitizenBudgetModel
  class ImpactsController < CitizenBudgetModelController
    before_action :authenticate_user!
    before_action :set_sensitivity
    before_action :set_sensitivity_section
    before_action :set_impact, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
      @impact = collection.new
      @variables = @sensitivity.variables
      ['Year 1', 'Year 2', 'Year 5'].each do |year|
        @variables.each do |variable|
          @impact.impact_variables.build(variable: variable, year: year)
        end
      end
    end

    def edit
    end

    def create
      @impact = collection.new(impact_params)

      if @impact.save
        redirect_to [@sensitivity, @sensitivity_section, @impact], notice: _('Impact was created.')
      else
        render :new
      end
    end

    def update
      if @impact.update(impact_params)
        respond_to do |format|
          format.html {
            redirect_to [@sensitivity, @sensitivity_section, @impact], notice: _('Impact was updated.')
          }
          format.json {
            render json: @impact.to_json
          }
        end
      else
        render :edit
      end
    end

    def destroy
      @impact.destroy
      redirect_to [@sensitivity, @sensitivity_section], notice: _('Impact was deleted.')
    end

  private

    def collection
      @collection ||= @sensitivity_section.impacts
    end

    def set_sensitivity
      @sensitivity = sensitivities.find(params[:sensitivity_id])
    end

    def set_sensitivity_section
      @sensitivity_section = @sensitivity.sensitivity_sections.find(params[:sensitivity_section_id])
    end

    def set_impact
      @impact = collection.find(params[:id])
    end

    def impact_params
      attribute_names = EconomicMeasure.globalize_attribute_names + [:machine_name, :is_public, :year_1_formula, :year_1_excel_formula, :year_2_formula, :year_2_excel_formula, :year_5_formula, :year_5_excel_formula, :impact_variables_attributes => [ :id, :year, :variable_id, :impact_id, :coefficient, :prepopulated_result ]]
      params.require(:impact).permit(*attribute_names)
    end
  end
end

app/controllers/citizen_budget_model/organizations_controller.rb
module CitizenBudgetModel
  class OrganizationsController < CitizenBudgetModelController
    before_action :authenticate_user!
    before_action :check_authorization!
    before_action :set_organization, only: [:show, :edit, :update, :destroy]

    def index
      @organizations = Organization.all.sort_by(&:name)
    end

    def show
    end

    def new
      @organization = Organization.new
    end

    def edit
    end

    def create
      @organization = Organization.new(organization_params)

      if @organization.save
        redirect_to @organization, notice: _('Organization was created.')
      else
        render :new
      end
    end

    def update
      if @organization.update(organization_params)
        redirect_to @organization, notice: _('Organization was updated.')
      else
        render :edit
      end
    end

    def destroy
      @organization.destroy
      redirect_to organizations_path, notice: _('Organization was deleted.')
    end

  private

    def set_organization
      @organization = Organization.find(params[:id])
    end

    def organization_params
      params.require(:organization).permit(*Organization.globalize_attribute_names)
    end
  end
end

app/controllers/citizen_budget_model/pages_controller.rb
module CitizenBudgetModel
  class PagesController < CitizenBudgetModelController
    def home
    end
  end
end

app/views/citizen_budget_model/sensitivities/edit.html.erb
<% content_for :breadcrumb do %>
<ol class="breadcrumb">
  <li><%= link_to _('Sensitivity Tables'), sensitivities_path %></li>
  <li><%= link_to @sensitivity.name, @sensitivity %></li>
  <li class="active"><%= _('Edit') %></li>
</ol>
<% end %>

<%= render 'form' %>

app/views/citizen_budget_model/sensitivities/new.html.erb
<% content_for :breadcrumb do %>
<ol class="breadcrumb">
  <li><%= link_to _('Sensitivity Tables'), sensitivities_path %></li>
  <li class="active"><%= _('Add') %></li>
</ol>
<% end %>

<%= render 'form' %>

app/views/citizen_budget_model/sensitivities/show.html.erb
<% content_for :breadcrumb do %>
<ol class="breadcrumb">
  <li><%= link_to _('Sensitivity Tables'), sensitivities_path %></li>
  <li class="active"><%= @sensitivity.name %>
    <%= link_to [:edit, @sensitivity], class: 'btn btn-default btn-xs', title: _('Edit') do %>
      <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
  </li>
</ol>
<% end %>

<h2><%= _('Publicly Editable Variables') %></h2>
<% if @sensitivity.variables.any? %>

<ul class="list-unstyled index sortable" data-sort-url="<%= sort_variable_sensitivity_path%>">
<% @sensitivity.variables.where(public_editable: true).each do |variable| %>
  <li id="<%= dom_id(variable) %>">
    <span class="glyphicon glyphicon-resize-vertical"></span>
    <%= link_to variable.name, [@sensitivity, variable] %>
    <span class="actions">
      <%= link_to [:edit, @sensitivity, variable] do %>
        <span class="glyphicon glyphicon-pencil"></span> <%= _('Edit') %>
      <% end %>
    </span>
  </li>
<% end %>
</ul>

<h2><%= _('Not Public Editable Variables') %></h2>
<ul class="list-unstyled index sortable" data-sort-url="<%= sort_variable_sensitivity_path%>">
<% @sensitivity.variables.where(public_editable: false).each do |variable| %>
  <li id="<%= dom_id(variable) %>">
    <span class="glyphicon glyphicon-resize-vertical"></span>
    <%= link_to variable.name, [@sensitivity, variable] %>
    <span class="actions">
      <%= link_to [:edit, @sensitivity, variable] do %>
        <span class="glyphicon glyphicon-pencil"></span> <%= _('Edit') %>
      <% end %>
    </span>
  </li>
<% end %>
</ul>

<% end %>

<p>
  <%= link_to(new_sensitivity_variable_path(@sensitivity), class: 'btn btn-primary') do %>
    <span class="glyphicon glyphicon-plus"></span> <%= _('Add a variable') %>
  <% end %>
</p>


<h2><%= _('Sections') %></h2>
<% if @sensitivity.sensitivity_sections.any? %>

  <ul class="list-unstyled index sortable">
<% @sensitivity.sensitivity_sections.each do |section| %>
  <li id="<%= dom_id(section) %>">
    <span class="glyphicon glyphicon-resize-vertical"></span>
    <%= link_to section.name, [@sensitivity, section] %>
    <span class="actions">
      <%= link_to [:edit, @sensitivity, section] do %>
        <span class="glyphicon glyphicon-pencil"></span> <%= _('Edit') %>
      <% end %>
    </span>
  </li>
<% end %>
</ul>
<% end %>
<p>
  <%= link_to(new_sensitivity_sensitivity_section_path(@sensitivity), class: 'btn btn-primary') do %>
    <span class="glyphicon glyphicon-plus"></span> <%= _('Add a section') %>
  <% end %>
</p>

<div class="row">
  <div class="col-lg-8 col-md-10 col-sm-12">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <% if I18n.locale.to_s == 'en-CA' %>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Instructions for using the sensitivity excel interface
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              <h4>The excel interface can be used for 3 things: </h4>
              <ol>
                <li>Setting a formula for an economic impact in a given year</li>

                <li>Testing the values that will be produced by the system on the front end</li>

                <li>Updating the values of the variables.</li>
              </ol>

              <p>To create a variable, a section, or an impact, one must use the blue buttons with the respective designation.</p>

              <p>The system currently supports 2 types of variables.  A Publicly Editable Variable that will be editable by users via
                sliders on the sensitivity table page and a Non-publicly Editable Variable that is only for use in the excel-like
                editing system.</p>

              <p>If you wish to use a Publicly Editable Variable in a formula, you must reference the respective User Input value
                (C column) in your formula.</p>

              <p>If you wish to use a Non-publicly Editable Variable you simply reference the respective cell in the B column.</p>

              <h4>Rules for using the excel-like interface:</h4>

              <ol>
                <li>You must reference cells with a capital letter. Lower case letters cannot be used</li>

                <li>You cannot use underscores (_) in your variable names</li>

                <li>You must only reference cells that have a numerical or formula value. The system will not parse text values</li>

                <li>Pre-calculated values are done top down, left to right.  So do not reference cells that are to the left of the
                cell you are editing</li>

                <li>Do not reference empty cells</li>

                <li>Do not use circular referencing in your formulas</li>

                <li>If you remove any variable, section, or impact, you must verify that your formulas still work as expected. If
                you have referenced something that no longer exists, the application will not be able to calculate the formula correctly</li>
              </ol>

            </div>
          </div>
        </div>
      <% end %>
      <% if I18n.locale.to_s == 'fr-CA' %>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseOne">
                Consignes pour l’utilisation de l’interface de sensibilité Excel
              </a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              <h4>L’interface d’Excel sert à trois fonctions :</h4>
              <ol>
                <li>créer une formule qui calcule les incidences économiques au cours d’une année donnée;</li>
                <li>mettre à l’essai les valeurs produites en amont par le système;</li>
                <li>actualiser les valeurs des variables.</li>
              </ol>
              <p>Pour créer une variable, une section ou encore une incidence, il faut utiliser les boutons bleus aux désignations respectives.</p>
              <p>Le système supporte en ce moment deux types de variables. En effet, il y a la variable que le public peut modifier à l’aide des
              curseurs de défilement sur la page de table sensible ainsi que la variable non modifiable par le public, qui est utilisée seulement
              dans le système modifiable similaire à Excel.</p>
              <p>Pour employer une variable modifiable par le public dans une formule, il vous faut créer la référence à la valeur d’entrée
              respective de l’utilisateur (colonne C) dans votre formule.</p>
              <p>Pour employer une variable non modifiable par le public, il vous faut simplement créer la référence à la cellule respective
              de la colonne B.</p>

              <h4>Règles d’utilisation de l’interface similaire à Excel</h4>
              <ol>
                <li>Il vous faut toujours utiliser la majuscule pour créer une référence à des cellules. Les minuscules ne peuvent être utilisées.</li>
                <li>Il faut éviter d’utiliser le caractère de soulignement (_) dans le nom des variables.</li>
                <li>Il faut créer la référence seulement à des cellules à valeur numérique ou à valeur d’une formule. Le système n’analysera pas
                les valeurs textuelles.</li>
                <li>Les valeurs précalculées sont exécutées de haut en bas et de gauche à droite. Il ne faut donc pas créer de référence à des
                cellules à gauche de celle que vous êtes en train de modifier.</li>
                <li>Il faut éviter les références à des cellules vides.</li>
                <li>Il faut éviter les références circulaires dans vos formules.</li>
                <li>Si une variable, une section ou une incidence est supprimée, il vous faut vérifier que vos formules fonctionnent comme prévu.
                Si vous avez créé une référence à une valeur qui n’existe plus, l’application ne pourra pas calculer correctement la formule.</li>
              </ol>

            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <div id="hot"></div>
  <div class="formula2"></div>
  <div class="status"></div>

  <script>

  var table = document.getElementById('hot');
  var data = <%= to_handsontable(@sensitivity).to_json.html_safe %>;

  function firstRowRenderer(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.fontWeight = 'bold';
  }

  var hot2 = new Handsontable(table, {
    data: data,
    formulas: true,
    rowHeaders: true,
    colHeaders: true,
    columns: [
      {data: 'variable_name'},
      {data: 'pbo_assumption', type:'numeric', format:'0.00'},
      {data: 'user_input', type:'numeric', format:'0.00'},
      {data: ''},
      {data: 'sname'},
      {data: 'year_1_excel_formula', type:'numeric', format:'0.00'},
      {data: 'year_2_excel_formula', type:'numeric', format:'0.00'},
      {data: 'year_5_excel_formula', type:'numeric', format:'0.00'}
    ],
    cells: function (row, col, prop) {
      var cellProperties = {};

      if (row === 2 || (row==0 && col == 0)) {
        cellProperties.renderer = firstRowRenderer;
      }

      if ((data[row]['bold'] !== undefined && $.inArray(col, data[row]['bold']) > -1)) {
        cellProperties.renderer = firstRowRenderer;
      }

      return cellProperties;
    },
    afterChange: function (change, source) {
      if(change != undefined) {
        var re = /([A-Za-z]+\d+)+/g;
        var str = change[0][3];
        var data_row = change[0][0];
        var data_attr = change[0][1];
        var m, m2;
        var formula = str;

        if (data_attr == 'year_1_excel_formula' || data_attr == 'year_2_excel_formula' || data_attr == 'year_5_excel_formula') {
          while ((m = re.exec(str)) !== null) {
            if (m.index === re.lastIndex) {
                re.lastIndex++;
            }
            m2 = /([A-Za-z]+)(\d+)+/g.exec(m[0]);
            if (m2) {
              var row = parseInt(m2[2])-1;
              var col = m2[1];

              if (data[row] !== undefined && data[row][col] !== undefined) {
                formula = formula.replace(m[0], data[row][col]);
              } else {
                $(".status").show().html("Error!");
              }
            }
          }
          var impact_url = data[data_row]['impact_url'];
          var year_formula = data_attr.replace("_excel", "");
          var impact = {};
          impact[year_formula] = formula.replace("=", "");
          impact[data_attr] = str;
          $.ajax({
            url: impact_url,
            dataType: 'json',
            method: 'PUT',
            data: {
              impact: impact
            }
          }).fail(function() {
            $(".status").show().html("Error!");
          }).done(function() {
            $(".status").show().html("Saved");
          }).complete(function(){
            setTimeout(function(){
              $(".status").fadeOut(1000);
            }, 2000);
          });

          $(".formula2").html(formula);
        } else if(data_attr == 'pbo_assumption') {
          if (data_row > 0) {

            var variable_url = data[data_row]['variable_url'];
            $.ajax({
              url: variable_url,
              dataType: 'json',
              method: 'PUT',
              data: {
                variable: {
                  pbo_assumption: change[0][3]
                }
              }
            }).fail(function() {
              $(".status").show().html("Error!");
            }).done(function() {
              $(".status").show().html("Saved");
            }).complete(function(){
              setTimeout(function(){
                $(".status").fadeOut(1000);
              }, 2000);
            });

          } else {
            while ((m = re.exec(str)) !== null) {
              if (m.index === re.lastIndex) {
                  re.lastIndex++;
              }
              m2 = /([A-Za-z]+)(\d+)+/g.exec(m[0]);
              if (m2) {
                var row = parseInt(m2[2])-1;
                var col = m2[1];

                var url = data[data_row]['url'];
                if (data[row] !== undefined && data[row][col] !== undefined) {
                  formula = formula.replace(m[0], data[row][col]);
                } else {
                  $(".status").show().html("Error!");
                }
              }
            }

            var sensitivity = {};
            sensitivity['default_formula'] = formula.replace("=", "");
            sensitivity['default_excel_formula'] = str;
            $.ajax({
              url: url,
              dataType: 'json',
              method: 'PUT',
              data: {
                sensitivity: sensitivity
              }
            }).fail(function() {
              $(".status").show().html("Error!");
            }).done(function() {
              $(".status").show().html("Saved");
            }).complete(function(){
              setTimeout(function(){
                $(".status").fadeOut(1000);
              }, 2000);
            });

            $(".formula2").html(formula);
          }
        }
      }
    }
  });

</script>