config/routes.rb
CitizenBudgetModel::Engine.routes.draw do
  devise_for :users, class_name: 'CitizenBudgetModel::User', module: :devise

  resources :translations, only: [:index, :create] do
    collection do
      get :export
    end
  end

  resources :organizations

  resources :users, except: [:show, :destroy]

  resources :policy_tables do
    member do
      post :sort
      post :activate
    end

    resources :policy_sections, except: [:index] do
      member do
        post :sort
      end

      resources :economic_measures, except: [:index]
    end
  end

  resources :sensitivities do
    member do
      post :sort
      post :sort_variable
    end

    resources :variables, except: [:index]

    resources :sensitivity_sections, except: [:index] do
      member do
        post :sort
      end
      resources :impacts, except: [:index]
    end
  end

  resources :simulators do
    member do
      post :sort
      post :activate
    end

    resources :sections, except: [:index] do
      member do
        post :sort
      end

      resources :questions, except: [:index]
    end
  end

  resources :questions

  namespace :citizen_budget_model do
    get 'pages/home'
  end

  root to: 'pages#home'
end

app/models/citizen_budget_model/economic_measure.rb
module CitizenBudgetModel
  class EconomicMeasure < ActiveRecord::Base
    acts_as_list scope: :policy_section_id, top_of_list: 0
    translates :name, :unit_name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :policy_section
    belongs_to :question

    validates_presence_of :policy_section_id
    validates_presence_of :question_id
    validates :name, 'citizen_budget_model/locale' => true
    validates_uniqueness_of :machine_name, scope: :policy_section_id, allow_blank: true
    validates_format_of :machine_name, with: /\A[a-z_][a-z_0-9]*\z/, allow_blank: true
    validates_numericality_of :year_1_value, :year_2_value, allow_blank: true
  end
end

app/models/citizen_budget_model/impact.rb
module CitizenBudgetModel
  class Impact < ActiveRecord::Base
    acts_as_list scope: :sensitivity_section_id, top_of_list: 0
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :sensitivity_section
    has_many :impact_variables, -> { order(:year) }, dependent: :destroy
    accepts_nested_attributes_for :impact_variables

    validates_presence_of :sensitivity_section_id
    validates_format_of :machine_name, with: /\A[a-z_][a-z_0-9]*\z/, allow_blank: true
    # @see http://www.postgresql.org/docs/9.3/static/sql-keywords-appendix.html
    # Nokogiri::HTML(open(url).read).xpath('//table/tbody/tr[td[2][text()="reserved"]]/td[1]//text()').map{|s| s.to_s.downcase}
    validates_exclusion_of :machine_name, in: %w(all analyse analyze and any
      array as asc asymmetric both case cast check collate column constraint
      create current_catalog current_date current_role current_time
      current_timestamp current_user default deferrable desc distinct do else
      end except false fetch for foreign from grant group having in initially
      intersect into lateral leading limit localtime localtimestamp not null
      offset on only or order placing primary references returning select
      session_user some symmetric table then to trailing true union unique user
      using variadic when where window with), allow_blank: true

    def year_1
      impact_variables.where(:year => 'Year 1')
    end

    def year_2
      impact_variables.where(:year => 'Year 2')
    end

    def year_5
      impact_variables.where(:year => 'Year 5')
    end
  end
end

app/models/citizen_budget_model/impact_variable.rb
module CitizenBudgetModel
  class ImpactVariable < ActiveRecord::Base
    belongs_to :impact
    belongs_to :variable

    validates_presence_of :impact_id
    validates_presence_of :variable_id
  end
end

app/models/citizen_budget_model/multiplier.rb
module CitizenBudgetModel
  class Multiplier < ActiveRecord::Base
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    belongs_to :simulator
    has_many :policy_sections

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true

    # Returns the equation or a default equation if not set.
    #
    # @return [String] an equation
    def working_equation
      default_equation
    end

    # Returns a default equation, where the difference between the chosen value
    # and the default value is multiplied by the unit value for each variable.
    #
    # @return [String] a default equation
    def default_equation
      equation = []
      policy_sections.each do |section|
        section.policies.each do |policy|
          equation << policy.question.working_equation
        end
        #section.questions.each do |question|
          #equation << question.working_equation
        #end
      end
      equation.reject(&:empty?).join(' + ')
    end


  end
end

app/models/citizen_budget_model/organization.rb
module CitizenBudgetModel
  class Organization < ActiveRecord::Base
    acts_as_paranoid
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    has_many :simulators, dependent: :destroy
    has_many :policy_tables, dependent: :destroy
    has_many :sentivities, dependent: :destroy
    has_many :users

    validates :name, 'citizen_budget_model/locale' => true
  end
end

app/models/citizen_budget_model/policy.rb
module CitizenBudgetModel
  class Policy < ActiveRecord::Base
    acts_as_list scope: :policy_section_id, top_of_list: 0
    translates :name, :unit_name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :policy_section
    belongs_to :question

    validates_presence_of :policy_section_id
    validates_uniqueness_of :machine_name, scope: :policy_section_id, allow_blank: true
    validates_format_of :machine_name, with: /\A[a-z_][a-z_0-9]*\z/, allow_blank: true
    validates_numericality_of :default_value, :year_1_value, :year_2_value, :minimum, :maximum, allow_blank: true
    validates_numericality_of :step, greater_than: 0, allow_blank: true

    validate :all_or_none_of_minimum_and_maximum_and_step_should_be_present
    validate :minimum_must_be_less_than_maximum

    def all_or_none_of_minimum_and_maximum_and_step_should_be_present
      unless minimum.present? && maximum.present? && step.present? || minimum.blank? && maximum.blank? && step.blank?
        [:minimum, :maximum, :step].each do |attribute|
          if send(attribute).blank?
            errors.add(attribute, :blank)
          end
        end
      end
    end

    def minimum_must_be_less_than_maximum
      if minimum.present? && maximum.present? && minimum.to_f >= maximum.to_f
        errors.add(:minimum, _('must be less than maximum'))
      end
    end
  end
end

app/models/citizen_budget_model/policy_section.rb
module CitizenBudgetModel
  class PolicySection < ActiveRecord::Base
    acts_as_list scope: :policy_table_id, top_of_list: 0
    translates :name, :popover, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :policy_table
    has_many :economic_measures, -> { order(:position) }, dependent: :destroy

    validates_presence_of :policy_table_id
    validates :name, 'citizen_budget_model/locale' => true
  end
end

app/models/citizen_budget_model/policy_table.rb
module CitizenBudgetModel
  class PolicyTable < ActiveRecord::Base
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    belongs_to :simulator
    has_many :policy_sections, -> { order(:position) }, dependent: :destroy

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true
    validates_numericality_of :growth_forecast, :employment_coefficient, greater_than: 0, allow_blank: true

    # Sets the simulator as active and all others as inactive.
    def activate!
      self.class.where(active: true).each do |policy_table|
        policy_table.update!(active: false)
      end
      update!(active: true)
    end

  end
end

app/models/citizen_budget_model/section.rb
module CitizenBudgetModel
  class Section < ActiveRecord::Base
    acts_as_list scope: :simulator_id, top_of_list: 0
    translates :title, :description, :modal, :popover, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :simulator
    has_many :questions, -> { order(:position) }, dependent: :destroy

    validates_presence_of :simulator_id

    # Returns the section's title or "Untitled"
    #
    # @return [String] the section's title or "Untitled"
    def display_name
      title.present? && title || _('Untitled')
    end
  end
end

app/models/citizen_budget_model/sensitivity.rb
module CitizenBudgetModel
  class Sensitivity < ActiveRecord::Base
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    has_many :variables, -> { order(:position) }, dependent: :destroy
    has_many :sensitivity_sections, -> { order(:position) }, dependent: :destroy

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true

  end
end

app/models/citizen_budget_model/sensitivity_section.rb
module CitizenBudgetModel
  class SensitivitySection < ActiveRecord::Base
    acts_as_list scope: :sensitivity_id, top_of_list: 0
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :sensitivity
    has_many :impacts, -> { order(:position) }, dependent: :destroy

    validates_presence_of :sensitivity_id

  end
end

app/models/citizen_budget_model/simulator.rb
module CitizenBudgetModel
  class Simulator < ActiveRecord::Base
    acts_as_paranoid
    translates :name, fallbacks_for_empty_translations: true
    globalize_accessors

    belongs_to :organization
    has_many :sections, -> { order(:position) }, dependent: :destroy

    validates_presence_of :organization_id
    validates :name, 'citizen_budget_model/locale' => true
    validates_numericality_of :total_revenue, greater_than: 0, only_integer: true, allow_blank: true
    validates :equation, 'citizen_budget_model/equation' => true, allow_blank: true

    # Sets the simulator as active and all others as inactive.
    def activate!
      self.class.where(active: true).each do |simulator|
        simulator.update!(active: false)
      end
      update!(active: true)
    end

    # Returns the equation or a default equation if not set.
    #
    # @return [String] an equation
    def working_equation
      if equation?
        equation
      else
        default_equation
      end
    end

    # Returns a default equation, where the difference between the chosen value
    # and the default value is multiplied by the unit value for each variable.
    #
    # @return [String] a default equation
    def default_equation
      equation = []
      sections.each do |section|
        section.questions.each do |question|
          equation << question.working_equation
        end
      end
      equation.reject(&:empty?).join(' + ')
    end

    # Solves the equation with the given variables' values.
    #
    # @param [Hash{Symbol,String=>Float,String}] variables variables
    # @return [Float] a solution
    def solve(variables)
      keys = []
      values = []

      variables.each do |key,value|
        keys << key.to_sym
        values << Float(value)
      end

      # Struct will raise a NameError, whereas OpenStruct will not.
      eval(working_equation, Struct.new(*keys).new(*values).instance_eval{binding})
    end
  end
end

app/controllers/citizen_budget_model/devise_controller.rb
module CitizenBudgetModel
  class DeviseController < CitizenBudgetModelController
    layout 'citizen_budget_model/devise'

    def after_sign_in_path_for(resource)
      simulators_path
    end
  end
end

app/controllers/citizen_budget_model/economic_measures_controller.rb
module CitizenBudgetModel
  class EconomicMeasuresController < CitizenBudgetModelController
    before_action :authenticate_user!
    before_action :set_policy_table
    before_action :set_policy_section
    before_action :set_economic_measure, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
      @economic_measure = collection.new
    end

    def edit
    end

    def create
      @economic_measure = collection.new(economic_measure_params)

      if @economic_measure.save
        redirect_to [@policy_table, @policy_section, @economic_measure], notice: _('Economic Measure was created.')
      else
        render :new
      end
    end

    def update
      if @economic_measure.update(economic_measure_params)
        redirect_to [@policy_table, @policy_section, @economic_measure], notice: _('Economic Measure was updated.')
      else
        render :edit
      end
    end

    def destroy
      @economic_measure.destroy
      redirect_to [@policy_table, @policy_section], notice: _('Economic Measure was deleted.')
    end

  private

    def collection
      @collection ||= @policy_section.economic_measures
    end

    def set_policy_table
      @policy_table = policy_tables.find(params[:policy_table_id])
    end

    def set_policy_section
      @policy_section = @policy_table.policy_sections.find(params[:policy_section_id])
    end

    def set_economic_measure
      @economic_measure = collection.find(params[:id])
    end

    def economic_measure_params
      attribute_names = EconomicMeasure.globalize_attribute_names + [:machine_name, :year_1_value, :year_2_value, :question_id]
      params.require(:economic_measure).permit(*attribute_names)
    end
  end
end

app/controllers/citizen_budget_model/impacts_controller.rb
module CitizenBudgetModel
  class ImpactsController < CitizenBudgetModelController
    before_action :authenticate_user!
    before_action :set_sensitivity
    before_action :set_sensitivity_section
    before_action :set_impact, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
      @impact = collection.new
      @variables = @sensitivity.variables
      ['Year 1', 'Year 2', 'Year 5'].each do |year|
        @variables.each do |variable|
          @impact.impact_variables.build(variable: variable, year: year)
        end
      end
    end

    def edit
    end

    def create
      @impact = collection.new(impact_params)

      if @impact.save
        redirect_to [@sensitivity, @sensitivity_section, @impact], notice: _('Impact was created.')
      else
        render :new
      end
    end

    def update
      if @impact.update(impact_params)
        respond_to do |format|
          format.html {
            redirect_to [@sensitivity, @sensitivity_section, @impact], notice: _('Impact was updated.')
          }
          format.json {
            render json: @impact.to_json
          }
        end
      else
        render :edit
      end
    end

    def destroy
      @impact.destroy
      redirect_to [@sensitivity, @sensitivity_section], notice: _('Impact was deleted.')
    end

  private

    def collection
      @collection ||= @sensitivity_section.impacts
    end

    def set_sensitivity
      @sensitivity = sensitivities.find(params[:sensitivity_id])
    end

    def set_sensitivity_section
      @sensitivity_section = @sensitivity.sensitivity_sections.find(params[:sensitivity_section_id])
    end

    def set_impact
      @impact = collection.find(params[:id])
    end

    def impact_params
      attribute_names = EconomicMeasure.globalize_attribute_names + [:machine_name, :is_public, :year_1_formula, :year_1_excel_formula, :year_2_formula, :year_2_excel_formula, :year_5_formula, :year_5_excel_formula, :impact_variables_attributes => [ :id, :year, :variable_id, :impact_id, :coefficient, :prepopulated_result ]]
      params.require(:impact).permit(*attribute_names)
    end
  end
end

app/controllers/citizen_budget_model/organizations_controller.rb
module CitizenBudgetModel
  class OrganizationsController < CitizenBudgetModelController
    before_action :authenticate_user!
    before_action :check_authorization!
    before_action :set_organization, only: [:show, :edit, :update, :destroy]

    def index
      @organizations = Organization.all.sort_by(&:name)
    end

    def show
    end

    def new
      @organization = Organization.new
    end

    def edit
    end

    def create
      @organization = Organization.new(organization_params)

      if @organization.save
        redirect_to @organization, notice: _('Organization was created.')
      else
        render :new
      end
    end

    def update
      if @organization.update(organization_params)
        redirect_to @organization, notice: _('Organization was updated.')
      else
        render :edit
      end
    end

    def destroy
      @organization.destroy
      redirect_to organizations_path, notice: _('Organization was deleted.')
    end

  private

    def set_organization
      @organization = Organization.find(params[:id])
    end

    def organization_params
      params.require(:organization).permit(*Organization.globalize_attribute_names)
    end
  end
end

app/controllers/citizen_budget_model/pages_controller.rb
module CitizenBudgetModel
  class PagesController < CitizenBudgetModelController
    def home
    end
  end
end

app/views/layouts/citizen_budget_model/admin.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><%= _('Admin') %></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css">
<%= stylesheet_link_tag 'citizen_budget_model/application', media: 'all' %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<%= javascript_include_tag 'citizen_budget_model/application' %>
<!-- ruleJS -->
<link rel="stylesheet" media="screen" href="https://handsontable.github.io/handsontable-ruleJS/lib/handsontable/handsontable.formula.css">

<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/lodash/lodash.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/underscore.string/underscore.string.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/moment/moment.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/numeral/numeral.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/numericjs/numeric.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/js-md5/md5.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/jstat/jstat.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/formulajs/formula.js"></script>

<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/js/parser.js"></script>
<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/js/ruleJS.js"></script>

<script data-jsfiddle="common" src="https://handsontable.github.io/handsontable-ruleJS/lib/handsontable/handsontable.formula.js"></script>


</head>
<body>

<nav class="navbar" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <%= _('Admin') %>
      </span>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to _('Simulators'), simulators_path %></li>
        <li><%= link_to _('Questions'), questions_path %></li>
        <li><%= link_to _('Policy Tables'), policy_tables_path %></li>
        <li><%= link_to _('Sensitivity Tables'), sensitivities_path %></li>
        <li><%= link_to _('Users'), users_path %></li>
      <% if admin? %>
        <li><%= link_to _('Organizations'), organizations_path %></li>
        <li><%= link_to _('Translations'), translations_path %></li>
      <% end %>
      </ul>
    <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-globe"> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% I18n.available_locales.each do |locale| %>
              <li><a href="?locale=<%= locale %>"><%= _(locale) %></a></li>
            <% end %>
          </ul>
        </li>
      <% if user_signed_in? %>
        <li><%= link_to _('Sign out'), destroy_user_session_path %></li>
      <% else %>
        <li><%= link_to _('Sign in'), new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield :breadcrumb %>

<div id="content" class="container-fluid">
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

<%= yield %>
</div>
</body>
</html>

app/views/layouts/citizen_budget_model/devise.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><%= _('Admin') %></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<%= stylesheet_link_tag 'citizen_budget_model/application', media: 'all' %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>

<nav class="navbar" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand">
        <%= _('Admin') %>
      </span>
    </div>
  </div>
</nav>

<%= yield :breadcrumb %>

<div class="container-fluid">
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

<%= yield %>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<%= javascript_include_tag 'citizen_budget_model/application' %>

</body>
</html>